ALTER TABLE pages DROP COLUMN IF EXISTS ocr_at;
ALTER TABLE pages DROP COLUMN IF EXISTS ocr_request_id;
ALTER TABLE pages DROP COLUMN IF EXISTS ocr_model;
ALTER TABLE pages DROP COLUMN IF EXISTS ocr_text;
