/**
 * Bookmarked PDF worksheet (P12).
 *
 * Same model as the XLSX renderer, so the two reconcile by construction. Bookmarks land on
 * sections so a preparer can jump to a schedule without scrolling, and the Judgment
 * Required section is last and unmissable.
 */
import PDFDocument from 'pdfkit';
import { formatCents } from '../lib/money.ts';
import type { WorksheetLine, WorksheetModel } from '../mapping/engine.ts';
import type { WorksheetContext } from './model.ts';

const MARGIN = 48;
const FONT = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const FONT_ITALIC = 'Helvetica-Oblique';

/** Group by the prefix before the colon so bookmarks follow the return's own structure. */
function sectionOf(lineRef: string): string {
  const prefix = lineRef.split(':')[0]!;
  switch (prefix) {
    case '1040': return 'Form 1040';
    case 'SCH1': return 'Schedule 1';
    case 'SCH1A': return 'Schedule 1-A';
    case 'SCHA': return 'Schedule A';
    case 'SCHB': return 'Schedule B';
    case 'SCHD': return 'Schedule D';
    case 'INFO': return 'Detail (not a return line)';
    case 'JUDGMENT': return 'Judgment Required';
    default: return prefix.startsWith('F') ? 'Supporting forms' : 'Other';
  }
}

export async function buildPdf(model: WorksheetModel, ctx: WorksheetContext): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'LETTER', margin: MARGIN, bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));

  const width = doc.page.width - MARGIN * 2;

  // ── cover ──────────────────────────────────────────────────────────────────
  doc.font(FONT_BOLD).fontSize(18).text('Vibe 1040 — source document worksheet');
  doc.moveDown(0.5);
  doc.font(FONT).fontSize(10);
  const meta: [string, string][] = [
    ['Bundle', ctx.bundleLabel],
    ['Tax year', String(model.taxYear)],
    ['Mapping version', model.mappingVersion],
    ['Generated', ctx.generatedAt.toISOString()],
    ['Generated by', ctx.generatedByName],
    ['Taxpayers', ctx.taxpayers.map((t) => `${t.displayName ?? 'unnamed'} (…${t.tinLast4})`).join('; ')],
    ['Documents', String(ctx.documentCount)],
  ];
  for (const [k, v] of meta) {
    doc.font(FONT_BOLD).text(`${k}: `, { continued: true }).font(FONT).text(v);
  }

  doc.moveDown(0.8);
  doc.font(FONT_ITALIC).fontSize(9).fillColor('#444444');
  doc.text(
    'This worksheet reports what the source documents say. It performs no tax computation and ' +
      'makes no determination about filing status, income characterization, deductions, or ' +
      'credits. Items requiring judgment are listed in the Judgment Required section.',
    { width },
  );
  doc.fillColor('#000000');

  if (ctx.softAnnotations.length) {
    doc.moveDown(0.8);
    doc.font(FONT_BOLD).fontSize(11).text('Annotations');
    doc.font(FONT).fontSize(9);
    for (const note of ctx.softAnnotations) {
      doc.text(`• ${note.message}`, { width, indent: 8 });
    }
  }

  // ── body, grouped into bookmarked sections ─────────────────────────────────
  const bySection = new Map<string, WorksheetLine[]>();
  for (const line of model.lines) {
    if (line.isJudgmentRequired) continue;
    const section = sectionOf(line.lineRef);
    const list = bySection.get(section) ?? [];
    list.push(line);
    bySection.set(section, list);
  }

  const outline = doc.outline;

  for (const [section, lines] of bySection) {
    doc.addPage();
    outline.addItem(section);
    doc.font(FONT_BOLD).fontSize(13).text(section);
    doc.moveDown(0.4);

    for (const line of lines) {
      const amount = line.notComputed
        ? 'not computed'
        : line.totalCents === null
          ? '—'
          : formatCents(line.totalCents);

      doc.font(FONT_BOLD).fontSize(10).fillColor('#000000');
      doc.text(line.label, { width: width - 110, continued: false });
      doc.moveUp();
      doc.text(amount, MARGIN + width - 100, doc.y, { width: 100, align: 'right' });
      doc.font(FONT).fontSize(8).fillColor('#666666');

      const counts =
        line.contributorCount === 0
          ? 'no contributing documents'
          : `${line.contributorCount} contributing document(s)` +
            (line.nullContributorCount > 0 ? `, ${line.nullContributorCount} with a blank box` : '');
      doc.text(counts, MARGIN, doc.y, { width });

      if (line.notComputed && line.notComputedReason) {
        doc.fillColor('#8a6d3b').text(line.notComputedReason, { width, indent: 8 });
      }

      doc.fillColor('#333333').fontSize(9);
      for (const c of line.contributions) {
        const value = c.valueCents === null ? 'blank' : formatCents(c.valueCents);
        const flags = [c.informational ? 'informational' : '', c.wasCorrected ? 'corrected' : '']
          .filter(Boolean)
          .join(', ');
        const source = ctx.documentLabels.get(c.documentId) ?? c.documentId;
        doc.text(
          `    ${c.formType} — ${c.fieldLabel}: ${value}${flags ? ` [${flags}]` : ''}  ·  ${source}`,
          { width, indent: 8 },
        );
      }
      doc.moveDown(0.5);
      doc.fillColor('#000000');
    }
  }

  // ── judgment required, always last ─────────────────────────────────────────
  doc.addPage();
  outline.addItem('Judgment Required');
  doc.font(FONT_BOLD).fontSize(13).fillColor('#8a1f11').text('Judgment Required');
  doc.fillColor('#000000').font(FONT).fontSize(9);
  doc.moveDown(0.3);
  doc.font(FONT_ITALIC).text(
    'These items are reported as printed. The app does not decide their treatment.',
    { width },
  );
  doc.moveDown(0.6);

  const judgmentLine = model.lines.find((l) => l.isJudgmentRequired);
  const items = judgmentLine?.contributions ?? [];

  if (!items.length) {
    doc.font(FONT).text('Nothing in this bundle required judgment.');
  } else {
    for (const c of items) {
      const value = c.valueCents === null ? 'blank' : formatCents(c.valueCents);
      doc.font(FONT_BOLD).fontSize(10).text(`${c.formType} — ${c.fieldLabel}: ${value}`, { width });
      doc.font(FONT).fontSize(9).fillColor('#444444');
      doc.text(c.judgmentReason ?? 'Requires preparer judgment.', { width, indent: 8 });
      doc.fontSize(8).fillColor('#666666').text(
        `Source: ${ctx.documentLabels.get(c.documentId) ?? c.documentId}`,
        { width, indent: 8 },
      );
      doc.fillColor('#000000');
      doc.moveDown(0.5);
    }
  }

  // Page numbers last, once the page count is known.
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    doc.font(FONT).fontSize(8).fillColor('#888888');
    doc.text(
      `${ctx.bundleLabel} · TY${model.taxYear} · page ${i + 1} of ${range.count}`,
      MARGIN,
      doc.page.height - 32,
      { width, align: 'center' },
    );
  }

  doc.end();
  return done;
}
