/**
 * XLSX worksheet (P12).
 *
 * Standard 1040 order, per-line totals with per-document detail beneath, provenance
 * references, the Judgment Required section, soft-failure annotations, and correction
 * indicators.
 *
 * The prior-year comparison column is present and empty: v1 has no client master and no
 * prior-season data (§7), and leaving the column out would mean redesigning the layout in
 * season two.
 */
import ExcelJS from 'exceljs';
import { centsToDollars } from '../lib/money.ts';
import type { WorksheetModel } from '../mapping/engine.ts';
import type { WorksheetContext } from './model.ts';

const HEADER_FILL: ExcelJS.Fill = {
  type: 'pattern',
  pattern: 'solid',
  fgColor: { argb: 'FF1F3864' },
};

export async function buildXlsx(model: WorksheetModel, ctx: WorksheetContext): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Vibe 1040';
  wb.created = ctx.generatedAt;

  // ── cover / table of contents ──────────────────────────────────────────────
  const cover = wb.addWorksheet('Summary');
  cover.columns = [{ width: 42 }, { width: 58 }];
  cover.addRow(['Vibe 1040 — source document worksheet']).font = { bold: true, size: 14 };
  cover.addRow([]);
  cover.addRow(['Bundle', ctx.bundleLabel]);
  cover.addRow(['Tax year', model.taxYear]);
  cover.addRow(['Mapping version', model.mappingVersion]);
  cover.addRow(['Generated', ctx.generatedAt.toISOString()]);
  cover.addRow(['Generated by', ctx.generatedByName]);
  cover.addRow(['Taxpayers', ctx.taxpayers.map((t) => `${t.displayName ?? 'unnamed'} (…${t.tinLast4})`).join('; ')]);
  cover.addRow(['Documents', String(ctx.documentCount)]);
  cover.addRow([]);
  const disclaimer = cover.addRow([
    'This worksheet reports what the source documents say. It performs no tax computation ' +
      'and makes no determination about filing status, income characterization, deductions, ' +
      'or credits. Items requiring judgment are listed in the Judgment Required section.',
  ]);
  disclaimer.font = { italic: true };
  cover.mergeCells(disclaimer.number, 1, disclaimer.number, 2);
  disclaimer.getCell(1).alignment = { wrapText: true, vertical: 'top' };
  cover.getRow(disclaimer.number).height = 46;

  if (ctx.softAnnotations.length) {
    cover.addRow([]);
    cover.addRow(['Annotations (soft check failures)']).font = { bold: true };
    for (const note of ctx.softAnnotations) {
      cover.addRow([note.checkKey, note.message]);
    }
  }

  // ── worksheet lines ────────────────────────────────────────────────────────
  const sheet = wb.addWorksheet('Worksheet');
  sheet.columns = [
    { header: 'Line', key: 'line', width: 16 },
    { header: 'Description', key: 'label', width: 62 },
    { header: 'Amount', key: 'amount', width: 16, style: { numFmt: '#,##0.00;(#,##0.00)' } },
    { header: 'Prior year', key: 'prior', width: 14, style: { numFmt: '#,##0.00;(#,##0.00)' } },
    { header: 'Docs', key: 'docs', width: 7 },
    { header: 'Blank', key: 'blank', width: 7 },
    { header: 'Source', key: 'source', width: 34 },
    { header: 'Note', key: 'note', width: 52 },
  ];
  const header = sheet.getRow(1);
  header.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  header.fill = HEADER_FILL;
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  for (const line of model.lines) {
    if (line.isJudgmentRequired) continue; // its own section, below

    const row = sheet.addRow({
      line: line.lineRef,
      label: line.label,
      amount: centsToDollars(line.totalCents),
      prior: null, // deliberately empty in v1 — see §7
      docs: line.contributorCount,
      blank: line.nullContributorCount,
      note: line.notComputed ? (line.notComputedReason ?? 'Not computed by this app.') : '',
    });
    row.font = { bold: true };

    if (line.notComputed) row.getCell('amount').font = { bold: true, italic: true, color: { argb: 'FF7F7F7F' } };

    for (const c of line.contributions) {
      const detail = sheet.addRow({
        line: '',
        label: `    ${c.formType} — ${c.fieldLabel}`,
        amount: centsToDollars(c.valueCents),
        prior: null,
        docs: '',
        blank: c.valueCents === null ? 'blank' : '',
        source: ctx.documentLabels.get(c.documentId) ?? c.documentId,
        note: [c.informational ? 'informational only' : '', c.wasCorrected ? 'corrected by reviewer' : '']
          .filter(Boolean)
          .join('; '),
      });
      detail.font = { size: 10, color: { argb: 'FF404040' } };
      if (c.wasCorrected) detail.getCell('amount').font = { size: 10, bold: true, color: { argb: 'FF9C5700' } };
      // A blank contributor is shown as blank, never as 0.00 — that distinction is the
      // whole point of the tool (§5).
      if (c.valueCents === null) detail.getCell('amount').value = null;
    }
  }

  // ── judgment required ──────────────────────────────────────────────────────
  const judgment = wb.addWorksheet('Judgment Required');
  judgment.columns = [
    { header: 'Form', key: 'form', width: 20 },
    { header: 'Field', key: 'field', width: 46 },
    { header: 'Amount', key: 'amount', width: 16, style: { numFmt: '#,##0.00;(#,##0.00)' } },
    { header: 'Source', key: 'source', width: 34 },
    { header: 'Why this needs a preparer', key: 'reason', width: 76 },
  ];
  const jHeader = judgment.getRow(1);
  jHeader.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  jHeader.fill = HEADER_FILL;
  judgment.views = [{ state: 'frozen', ySplit: 1 }];

  const judgmentLine = model.lines.find((l) => l.isJudgmentRequired);
  for (const c of judgmentLine?.contributions ?? []) {
    judgment.addRow({
      form: c.formType,
      field: c.fieldLabel,
      amount: centsToDollars(c.valueCents),
      source: ctx.documentLabels.get(c.documentId) ?? c.documentId,
      reason: c.judgmentReason ?? 'Requires preparer judgment.',
    });
  }
  if (!judgmentLine?.contributions.length) {
    judgment.addRow({ form: '—', field: 'Nothing in this bundle required judgment.', reason: '' });
  }

  const out = await wb.xlsx.writeBuffer();
  return Buffer.from(out);
}
