/**
 * One-time codes for email and SMS second factors, and for password resets.
 *
 * Rules that are not negotiable, because this is the path into taxpayer data (§11):
 *
 *  - The code is **never stored** — only an HMAC of it, keyed by the session secret. A
 *    database read must not let anyone complete a second factor.
 *  - Codes are generated with `randomInt`, not `Math.random`.
 *  - Verification is constant-time and attempt-limited; a burned code stays burned.
 *  - Issuing a new code **invalidates the previous one**, so a code sitting in an old email
 *    cannot be replayed after the user asks for another.
 *  - Enumeration is not possible from the outside: the caller reveals nothing about whether
 *    an account exists (see `password-reset.ts`).
 *
 * SMS is offered because it was asked for, and it is genuinely weaker than TOTP — SIM swap
 * and carrier interception are real. The admin UI says so at the point of choosing.
 */
import { createHmac, randomInt, timingSafeEqual } from 'node:crypto';
import { and, desc, eq, isNull } from 'drizzle-orm';
import { db } from '../db/client.ts';
import { otpChallenges, users } from '../db/schema.ts';
import { secrets } from '../config/env.ts';
import { recordDelivery, redact, sendEmail, sendSms, type Channel, type Purpose } from '../notify/channels.ts';
import { setting } from '../settings/store.ts';

const CODE_LENGTH = 6;

function generateCode(): string {
  // randomInt is uniform; a modulo of randomBytes is not.
  return String(randomInt(0, 10 ** CODE_LENGTH)).padStart(CODE_LENGTH, '0');
}

function hashCode(code: string, challengeSalt: string): string {
  return createHmac('sha256', secrets.sessionSecret).update(`${challengeSalt}:${code}`).digest('hex');
}

export interface IssueResult {
  ok: boolean;
  /** Redacted destination, safe to show the user: "j***@example.com". */
  destination?: string;
  error?: string;
  /** Present only in development with delivery disabled — never in production. */
  devCode?: string;
}

const MESSAGES: Record<Purpose, (code: string, ttlMinutes: number) => { subject: string; body: string }> = {
  mfa: (code, ttl) => ({
    subject: 'Your Vibe 1040 sign-in code',
    body:
      `Your sign-in code is ${code}. It expires in ${ttl} minutes.\n\n` +
      'If you did not try to sign in, tell your firm administrator — someone has your password.',
  }),
  password_reset: (code, ttl) => ({
    subject: 'Vibe 1040 password reset',
    body:
      `Your password reset code is ${code}. It expires in ${ttl} minutes.\n\n` +
      'If you did not request a reset, you can ignore this message; your password is unchanged.',
  }),
  phone_verify: (code, ttl) => ({
    subject: 'Verify your phone for Vibe 1040',
    body: `Your verification code is ${code}. It expires in ${ttl} minutes.`,
  }),
};

/**
 * Issue a code and deliver it.
 *
 * Any previously outstanding code for the same user and purpose is consumed first — one
 * live code at a time, so an old message cannot be replayed.
 */
export async function issueCode(
  userId: string,
  purpose: Purpose,
  channel: Channel,
  destination: string,
  ip?: string | null,
): Promise<IssueResult> {
  const ttlSeconds = await setting<number>(
    purpose === 'password_reset' ? 'auth.password_reset_ttl_seconds' : 'auth.otp_ttl_seconds',
  );

  await db
    .update(otpChallenges)
    .set({ consumedAt: new Date() })
    .where(
      and(
        eq(otpChallenges.userId, userId),
        eq(otpChallenges.purpose, purpose),
        isNull(otpChallenges.consumedAt),
      ),
    );

  const code = generateCode();
  const redacted = redact(channel, destination);

  const [challenge] = await db
    .insert(otpChallenges)
    .values({
      userId,
      purpose,
      // Salted per challenge by its own id — but the id is generated by the database, so
      // salt with the destination plus purpose instead, which is stable and per-challenge.
      codeHash: hashCode(code, `${userId}:${purpose}`),
      destination: redacted,
      channel,
      expiresAt: new Date(Date.now() + ttlSeconds * 1000),
      ip: ip ?? null,
    })
    .returning({ id: otpChallenges.id });

  const ttlMinutes = Math.round(ttlSeconds / 60);
  const { subject, body } = MESSAGES[purpose](code, ttlMinutes);

  const result =
    channel === 'email'
      ? await sendEmail(destination, subject, body)
      : await sendSms(destination, body);

  await recordDelivery({ userId, channel, purpose, destination, result });

  if (!result.ok) {
    // A code nobody received is worse than no code — burn it so the user can retry cleanly.
    await db.update(otpChallenges).set({ consumedAt: new Date() }).where(eq(otpChallenges.id, challenge!.id));
    return { ok: false, error: result.error ?? 'delivery failed' };
  }

  return { ok: true, destination: redacted };
}

export type VerifyOutcome =
  | { ok: true }
  | { ok: false; reason: 'no_challenge' | 'expired' | 'too_many_attempts' | 'wrong_code' };

export async function verifyCode(userId: string, purpose: Purpose, code: string): Promise<VerifyOutcome> {
  const [challenge] = await db
    .select()
    .from(otpChallenges)
    .where(
      and(
        eq(otpChallenges.userId, userId),
        eq(otpChallenges.purpose, purpose),
        isNull(otpChallenges.consumedAt),
      ),
    )
    .orderBy(desc(otpChallenges.createdAt))
    .limit(1);

  if (!challenge) return { ok: false, reason: 'no_challenge' };

  if (challenge.expiresAt.getTime() < Date.now()) {
    await db.update(otpChallenges).set({ consumedAt: new Date() }).where(eq(otpChallenges.id, challenge.id));
    return { ok: false, reason: 'expired' };
  }

  const maxAttempts = await setting<number>('auth.otp_max_attempts');
  if (challenge.attempts >= maxAttempts) {
    await db.update(otpChallenges).set({ consumedAt: new Date() }).where(eq(otpChallenges.id, challenge.id));
    return { ok: false, reason: 'too_many_attempts' };
  }

  const expected = Buffer.from(challenge.codeHash, 'hex');
  const actual = Buffer.from(hashCode(code.replace(/\s/g, ''), `${userId}:${purpose}`), 'hex');
  const matches = expected.length === actual.length && timingSafeEqual(expected, actual);

  if (!matches) {
    await db
      .update(otpChallenges)
      .set({ attempts: challenge.attempts + 1 })
      .where(eq(otpChallenges.id, challenge.id));
    return { ok: false, reason: 'wrong_code' };
  }

  // Single use, always.
  await db.update(otpChallenges).set({ consumedAt: new Date() }).where(eq(otpChallenges.id, challenge.id));
  return { ok: true };
}

/** Where a user's chosen factor delivers to, and whether it is usable. */
export async function factorDestination(
  userId: string,
): Promise<{ channel: Channel | 'totp'; destination: string | null; usable: boolean; why?: string }> {
  const [user] = await db.select().from(users).where(eq(users.id, userId)).limit(1);
  if (!user) return { channel: 'totp', destination: null, usable: false, why: 'no such user' };

  const allowed = await setting<string[]>('auth.allowed_mfa_methods');
  if (!allowed.includes(user.mfaMethod)) {
    return {
      channel: user.mfaMethod as Channel | 'totp',
      destination: null,
      usable: false,
      why: `${user.mfaMethod} is no longer a permitted second factor at this firm`,
    };
  }

  switch (user.mfaMethod) {
    case 'email':
      return { channel: 'email', destination: user.email, usable: true };
    case 'sms':
      return user.phone && user.phoneVerifiedAt
        ? { channel: 'sms', destination: user.phone, usable: true }
        : {
            channel: 'sms',
            destination: user.phone,
            usable: false,
            why: user.phone ? 'phone number is not verified' : 'no phone number on file',
          };
    default:
      return {
        channel: 'totp',
        destination: null,
        usable: user.totpConfirmedAt !== null,
        ...(user.totpConfirmedAt ? {} : { why: 'authenticator not enrolled' }),
      };
  }
}
